#
# Default properties for OSIAM
#

logging.level:
  # Default log level is ERROR
  '': ERROR
  org.springframework: WARN
  org.osiam: INFO

spring.thymeleaf.prefix: file:${osiam.home}/templates/web/
spring.jpa.hibernate.naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy
